namespace AlgoForge.Models
{
    public class Photo
    {
        public int Id { get; set; }

        public int AlbumId { get; set; }
        public Album Album { get; set; } = null!;

        // Three renditions per photo, generated by the face-worker pass.
        public string OriginalBlobUrl { get; set; } = string.Empty;
        public string DisplayBlobUrl { get; set; } = string.Empty;
        public string ThumbnailBlobUrl { get; set; } = string.Empty;

        public string UploadedByUserId { get; set; } = string.Empty;
        public DateTime UploadedAt { get; set; } = DateTime.UtcNow;

        // True once the queued face-detection pass has completed for this photo.
        public bool FaceProcessingComplete { get; set; } = false;

        // Soft delete / restore (never a hard delete of the photo row)
        public bool IsDeleted { get; set; } = false;
        public DateTime? DeletedAt { get; set; }
        public string? DeletedByUserId { get; set; }

        // Metadata attendees/photographers can edit
        public string? Caption { get; set; }
        public DateTime? TakenAt { get; set; }

        public ICollection<FaceDetection> FaceDetections { get; set; } = new List<FaceDetection>();
        public ICollection<Comment> Comments { get; set; } = new List<Comment>();
    }
}
